name: Enter the Dingo
favicon: null
layout_spectrum: 0.16621
typography_spectrum: 0
title: Enter the Dingo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a51207'
    - '#171717'
    - '#d9b36d'
    - '#ffffff'
    - '#977940'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
